language: node_js
node_js:
  - "6"
os:
- linux
- osx

addons:
  apt:
    packages:
    - rpm

env:
  matrix:
  - NODE_INSTALLER=npm
  - NODE_INSTALLER=yarn

script:
- if [[ "$NODE_INSTALLER" = "yarn" ]]; then npm i -g yarn; fi
- npm run test -- --installer=$NODE_INSTALLER
